version: '3.8'
services:
  backend:
    container_name: node-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    